[package]
name = "iobewi-esp-device"
workspace = "../../../targets/esp32"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP implementation of portable IOBEWI device identity and metadata capabilities"

[features]
default = []
esp32c3 = ["esp-hal/esp32c3"]
esp32s3 = ["esp-hal/esp32s3"]

[dependencies]
iobewi-device = { path = "../core" }
esp-hal = { version = "~1.2", default-features = false, features = ["unstable"] }
esp-metadata-generated = "~0.5"
