[package]
name = "iobewi-esp-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP HTTPS listener implementing the portable IOBEWI HTTP contract"

[features]
default = []
esp32s3 = ["esp-hal/esp32s3", "iobewi-esp-tls/esp32s3"]

[dependencies]
iobewi-http = { git = "https://github.com/iobewi/iobewi", rev = "c1181c86a13821ef3cd19d656b84c23baaa1191d" }
iobewi-esp-tls = { path = "../tls", default-features = false, features = ["picoserve"] }
esp-hal = { version = "~1.1.0", default-features = false, features = ["unstable"] }
embassy-net = { version = "0.9.1", default-features = false, features = ["tcp", "medium-ethernet"] }
embassy-time = { version = "0.5.0", default-features = false }
picoserve = { version = "0.20.0", default-features = false, features = ["embassy", "alloc"] }
log = "0.4"
