[package]
name = "iobewi-esp-https"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP TLS handshake and HTTPS listener for IOBEWI"

[features]
default = []
esp32s3 = ["esp-hal/esp32s3", "iobewi-esp-tls/esp32s3", "iobewi-esp-http/esp32s3"]

[dependencies]
iobewi-https = { git = "https://github.com/iobewi/iobewi", rev = "2f2d70a69968ef0b442932ac0c00b983ccce6a7c" }
iobewi-esp-http = { path = "../http", default-features = false }
iobewi-esp-tls = { path = "../tls", default-features = false, features = ["picoserve"] }
esp-hal = { version = "~1.1.0", default-features = false, features = ["unstable"] }
embassy-net = { version = "0.9.1", default-features = false, features = ["tcp", "medium-ethernet"] }
embassy-time = { version = "0.5.0", default-features = false }
picoserve = { version = "0.20.0", default-features = false, features = ["embassy", "alloc"] }
log = "0.4"
