[workspace]
members = ["services/http", "services/https", "fs/config", "services/ota", "services/wifi", "services/tls", "services/log-stream", "services/ntp", "services/transport", "services/indicator", "services/runtime", "services/device", "services/entropy"]
default-members = ["services/http", "services/https", "fs/config", "services/ota", "services/wifi", "services/tls", "services/log-stream", "services/ntp", "services/transport", "services/indicator", "services/runtime", "services/device", "services/entropy"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/iobewi/iobewi"
