[package]
name = "iobewi"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/iobewi/iobewi"
description = "Portable embedded service framework for IOBEWI"

[features]
default = ["http"]
http = ["dep:picoserve", "dep:log"]

[dependencies]
log = { version = "0.4", optional = true }
picoserve = { version = "0.20.0", default-features = false, features = ["embassy", "alloc"], optional = true }
