[package]
name = "iobewi-esp-entropy"
workspace = "../../../iobewi-esp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP implementation of the portable IOBEWI entropy capability"

[features]
default = []
esp32c3 = ["esp-hal/esp32c3"]
esp32s3 = ["esp-hal/esp32s3"]

[dependencies]
iobewi-entropy = { path = "../../../crypto/rng" }
esp-hal = { version = "~1.1.0", default-features = false }
