[package]
name = "iobewi-log-stream"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Portable outbound WebSocket streaming of captured logs"

[dependencies]
iobewi-log = { path = "../core" }
iobewi-http-server = { path = "../../net/http/server" }
iobewi-net-io = { path = "../../net/io" }
iobewi-net-tls-core = { path = "../../net/tls/core" }
embassy-time = { version = "0.5.0", default-features = false }
embedded-io-async = "0.7.0"
log = "0.4"
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
