name: Rust ESP
on:
  push:
jobs:
  check-host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
  check-esp32s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          buildtargets: esp32s3
      - run: cargo +esp check -Z build-std=core,alloc --target xtensa-esp32s3-none-elf -p iobewi-esp-http --features esp32s3
      - run: cargo +esp check -Z build-std=core,alloc --target xtensa-esp32s3-none-elf -p iobewi-esp-https --features esp32s3
      - run: cargo +esp check -Z build-std=core,alloc --target xtensa-esp32s3-none-elf -p iobewi-esp-ota --features esp32s3,shared-flash
      - run: cargo +esp check -Z build-std=core,alloc --target xtensa-esp32s3-none-elf -p iobewi-esp-config-space --features esp32s3
      - run: cargo +esp check -Z build-std=core,alloc --target xtensa-esp32s3-none-elf -p iobewi-esp-wifi --features esp32s3
      - run: cargo +esp check -Z build-std=core,alloc --target xtensa-esp32s3-none-elf -p iobewi-esp-tls --features esp32s3,embassy-net
      - run: cargo +esp check -Z build-std=core,alloc --target xtensa-esp32s3-none-elf -p iobewi-esp-watchdog --features esp32s3
      - run: cargo +esp check -Z build-std=core,alloc --target xtensa-esp32s3-none-elf -p iobewi-esp-indicator --features esp32s3
      - run: cargo +esp check -Z build-std=core,alloc --target xtensa-esp32s3-none-elf -p iobewi-esp-runtime --features esp32s3
      - run: cargo +esp check -Z build-std=core,alloc --target xtensa-esp32s3-none-elf -p iobewi-esp-device --features esp32s3
      - run: cargo +esp check -Z build-std=core,alloc --target xtensa-esp32s3-none-elf -p iobewi-esp-entropy --features esp32s3
  check-bootloader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          buildtargets: esp32s3
      - run: cargo +esp check --manifest-path bootloader/esp/Cargo.toml --locked -Z build-std=core,alloc --target xtensa-esp32s3-none-elf --features esp32s3
