[package]
name = "iobewi-esp-log-stream"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP RNG port for the portable log stream (Entropy)"

[features]
default = []
esp32s3 = ["dep:esp-hal", "esp-hal/esp32s3"]

[dependencies]
iobewi-log-stream = { path = "../../../log/stream" }
esp-hal = { version = "~1.1.0", default-features = false, features = ["unstable"], optional = true }
