[workspace]

[package]
edition = "2024"
name = "iobewi-esp-bootloader"
rust-version = "1.88"
version = "0.1.0"
license = "MIT"
description = "ESP second-stage bootloader executor using IOBEWI OTA lifecycle semantics"

[[bin]]
name = "iobewi-esp-bootloader"
path = "src/main.rs"

[features]
default = []
esp32c3 = [
  "esp-hal/esp32c3",
  "esp-hal/rt",
  "esp-println/esp32c3",
  "esp-println/jtag-serial",
  "iobewi-esp-boot/esp32c3",
]
esp32s3 = [
  "esp-hal/esp32s3",
  "esp-hal/rt",
  "esp-println/esp32s3",
  "esp-println/jtag-serial",
  "iobewi-esp-boot/esp32s3",
]

[dependencies]
esp-hal = { version = "~1.2", default-features = false }
esp-println = { version = "~0.18", default-features = false }
iobewi-esp-boot = { path = "../../arch/esp32/boot", default-features = false }
iobewi-esp-platform = { path = "../../arch/esp32/platform" }
iobewi-firmware-boot = { path = "../../firmware/boot" }
iobewi-firmware-image = { path = "../../firmware/image", default-features = false }

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
panic = "abort"
debug = 2
overflow-checks = false
