[package]
name = "iobewi-wifi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Portable Wi-Fi provisioning, credential storage and reconnection service"

[dependencies]
iobewi-config-space = { path = "../../fs/config" }
log = { version = "0.4", default-features = false }
