name: Rust
on:
  push:
  pull_request:
jobs:
  host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --workspace --all-features
      - run: cargo check --workspace --no-default-features
      - run: cargo test -p iobewi-config-space
      - run: cargo test -p iobewi-http
      - run: cargo test -p iobewi-log-stream
      - run: cargo test -p iobewi-wifi
      - run: cargo test -p iobewi-tls
      - run: cargo test -p iobewi-tls --features http
      - run: cargo test -p iobewi-ota
      - run: cargo test -p iobewi-ota --features http
