[package]
name = "iobewi-esp-nvs"
workspace = "../../../targets/esp32"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "ESP NVS hardware bridge over iobewi-esp-flash"
keywords = ["esp32", "nvs", "embedded", "no-std"]
categories = ["embedded", "hardware-support", "no-std"]

[features]
default = []
esp32c3 = [
  "iobewi-esp-flash/esp32c3",
  "esp-nvs/esp32c3",
  "esp-storage/esp32c3",
]
esp32s3 = [
  "iobewi-esp-flash/esp32s3",
  "esp-nvs/esp32s3",
  "esp-storage/esp32s3",
]

[dependencies]
embedded-storage = "0.3.1"
iobewi-esp-flash = { path = "../../../drivers/flash/esp32" }
esp-nvs = { version = "0.5.0", default-features = false }
esp-storage = { version = "~0.10", default-features = false, features = ["embedded-storage"] }
